site_name: Bitrise DevCenter
theme: material
repo_name: 'GitHub'
repo_url: 'https://github.com/bitrise-io/devcenter'

pages:
- Bitrise DevCenter: index.md
- Getting Started:
  - What is Bitrise?: getting-started/index.md
  - Builds & Workflows: getting-started/builds-and-workflows.md
  - Code Security: getting-started/code-security.md
- Infrastructure:
  - Virtual Machines: infrastructure/virtual-machines.md
  - Available Stacks: infrastructure/available-stacks.md
- Signing up:
  - Signing up with GitHub: signing-up/signing-up-with-github.md
  - Signing up with Bitbucket: signing-up/signing-up-with-bitbucket.md
  - Signing up with email: signing-up/signing-up-with-email.md
  - Trial after signing up: signing-up/trial-after-signing-up.md
- Adding a new app:
  - Adding a new app: adding-a-new-app/index.md
  - Connecting a repository: adding-a-new-app/connecting-a-repository.md
  - Setting up SSH keys: adding-a-new-app/setting-up-ssh-keys.md
  - Setting up configuration: adding-a-new-app/setting-up-configuration.md
- Tutorials:
  - Community Created: tutorials/community-created.md
  - Create signed APK on bitrise.io: tutorials/create-signed-apk-on-bitrise.md
- Team management:
  - Adding a new team member: team-management/index.md
  - Changing the owner of an app: team-management/changing-the-owner-of-an-app.md
- Webhooks:
  - Adding webhooks: webhooks/index.md
  - Adding a GitHub webhook: webhooks/adding-a-github-webhook.md
- Caching:
  - About caching: caching/about-caching.md
  - Caching Cocoapods: caching/caching-cocoapods.md
  - Caching Gradle: caching/caching-gradle.md
  - Caching Ruby GEMs: caching/caching-ruby-gems.md
- CLI:
  - Why you should use the Steplib: cli/why-you-should-use-the-steplib.md
- iOS:
  - Code Signing: ios/code-signing.md
  - Uploading certificates: ios/uploading-certificates.md
  - Resigning an IPA: ios/resigning-an-ipa.md
  - List of known Xcode issues: ios/known-xcode-issues.md
- Docker:
  - How to run your build locally in Docker: docker/run-your-build-locally-in-docker.md
  # - How we build our images: docker/how-we-build-our-images.md
- Tips & Tricks:
  - Attach any file as an Artifact to the Build: tips-and-tricks/attach-any-file-to-build.md
  - Expose an Environment Variable and use it in another Step: tips-and-tricks/expose-environment-variable.md
  - Don't mark the Build as failed if a given step would fail (ignore the error of the Step): tips-and-tricks/dont-mark-build-failed-if-step-fails.md
  - Enable/Disable a step (optionally, based on a condition): tips-and-tricks/disable-a-step-by-condition.md
  - "Xcode Archive: export options": tips-and-tricks/xcodebuild-export-options.md
  - "Install Any Additional Tool": tips-and-tricks/install-additional-tools.md

markdown_extensions:
  - codehilite(css_class=code)
  - admonition
  - toc:
      permalink: 'âš“'

extra:
  palette:
    primary: 'deep purple'
    accent: 'deep purple'
    extra:
  logo: 'img/logo.svg'
  font:
    text: 'Roboto'
    code: 'Source Code Pro'
extra_css: ['stylesheets/extra.css']
