---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: forestry-help.md
  label: Forestry User Guide
  read_only: true
- type: directory
  path: _articles/reviews
  label: For review
  create: all
  match: "**/*"
- type: heading
  label: DevCenter articles
- type: directory
  path: _articles
  label: Bitrise Devcenter - What is Bitrise
  create: all
  match: index.md
- type: directory
  path: _articles/getting-started
  label: Getting started
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: _articles/infrastructure
  label: Infrastructure
  create: all
  match: "**/*"
- type: directory
  path: _articles/team-management
  label: Teams and organizations
  create: all
  match: "**/*"
- type: directory
  path: _articles/webhooks
  label: Webhooks
  create: all
  match: "**/*"
- type: directory
  path: _articles/builds
  label: Builds
  create: all
  match: "**/*"
- type: directory
  path: _articles/code-signing
  label: Code signing
  create: all
  match: "**/*"
- type: directory
  path: _articles/caching
  label: Caching
  create: all
  match: "**/*"
- type: directory
  path: _articles/bitrise-cli
  label: Bitrise CLI
  create: all
  match: "**/*"
- type: directory
  path: _articles/testing
  label: Testing
  create: all
  match: "**/*"
- type: directory
  path: _articles/deploy
  label: Deployment
  create: all
  match: "**/*"
- type: directory
  path: _articles/tutorials
  label: Tutorials
  create: all
  match: "**/*"
- type: directory
  path: _articles/tips-and-tricks
  label: Tips and tricks
  create: all
  match: "**/*"
- type: directory
  path: _articles/faq
  label: FAQ
  create: all
  match: "**/*"
- type: directory
  path: _articles/troubleshooting
  label: Troubleshooting
  create: all
  match: "**/*"
- type: directory
  path: _articles/tools
  label: Tools
  create: all
  match: "**/*"
- type: heading
  label: Data files
- type: document
  path: _config.yml
  label: _config.yml
- type: directory
  path: _data
  label: Forestry data files - MENUS.YML here
  create: all
  match: "**/*"
- type: directory
  path: ".forestry"
  label: ".forestry"
  create: all
  match: "**/*"
- type: directory
  path: _layouts
  label: _layouts
  create: all
  match: "**/*"
- type: directory
  path: _includes
  label: _includes (HTML)
  create: all
  match: "**/*"
upload_dir: _articles/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
